<?php

########################################################################
# Extension Manager/Repository config file for ext: "word"
#
# Auto generated by Extension Builder 2013-02-15
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Office Renderer',
	'description' => 'iresults interface to the PHPExcel and PHPWord packagey',
	'category' => 'services',
	'author' => 'Andreas Thurnheer-Meier, Daniel Corn',
	'author_email' => 'tma@iresults.li, cod@iresults.li',
	'author_company' => 'iresults, iresults',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '0.1',
	'constraints' => array(
		'depends' => array(
			'cms' => '',
			'extbase' => '',
			'fluid' => '',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>